// <auto-generated />
using System;
using DiplomaticMailBot.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomaticMailBot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225070659_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SlotInstanceId")
                        .HasColumnType("integer");

                    b.Property<long>("SubmitterId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SlotInstanceId");

                    b.HasIndex(new[] { "MessageId", "SlotInstanceId" }, "DiplomaticMailCandidate_Unique_IX")
                        .IsUnique();

                    b.ToTable("DiplomaticMailCandidates");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiplomaticMailCandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotInstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StatusDetails")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaticMailCandidateId");

                    b.HasIndex(new[] { "SlotInstanceId" }, "DiplomaticMailOutbox_SlotInstanceId_IX")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "DiplomaticMailOutbox_Status_IX");

                    b.ToTable("DiplomaticMailOutbox");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotInstanceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SlotInstanceId" }, "DiplomaticMailPoll_SlotInstanceId_Unique_IX")
                        .IsUnique();

                    b.ToTable("DiplomaticMailPolls");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceChatId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetChatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetChatId");

                    b.HasIndex(new[] { "SourceChatId", "TargetChatId" }, "DiplomaticRelation_Unique_IX")
                        .IsUnique();

                    b.ToTable("DiplomaticRelations");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.RegisteredChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatAlias")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChatTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex(new[] { "ChatAlias" }, "RegisteredChat_ChatAlias_Unique_IX")
                        .IsUnique();

                    b.HasIndex(new[] { "ChatId" }, "RegisteredChat_ChatId_Unique_IX")
                        .IsUnique();

                    b.ToTable("RegisteredChats");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.SlotInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FromChatId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ToChatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromChatId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.HasIndex("ToChatId");

                    b.HasIndex(new[] { "Date", "TemplateId", "FromChatId", "ToChatId" }, "SlotInstance_Unique_IX")
                        .IsUnique();

                    b.ToTable("SlotInstances");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.SlotTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("VoteEndAt")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("VoteStartAt")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("SlotTemplates");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailCandidate", b =>
                {
                    b.HasOne("DiplomaticMailBot.Entities.SlotInstance", "SlotInstance")
                        .WithMany("DiplomaticMailCandidates")
                        .HasForeignKey("SlotInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlotInstance");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailOutbox", b =>
                {
                    b.HasOne("DiplomaticMailBot.Entities.DiplomaticMailCandidate", "DiplomaticMailCandidate")
                        .WithMany()
                        .HasForeignKey("DiplomaticMailCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaticMailBot.Entities.SlotInstance", "SlotInstance")
                        .WithMany()
                        .HasForeignKey("SlotInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiplomaticMailCandidate");

                    b.Navigation("SlotInstance");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticMailPoll", b =>
                {
                    b.HasOne("DiplomaticMailBot.Entities.SlotInstance", "SlotInstance")
                        .WithMany()
                        .HasForeignKey("SlotInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlotInstance");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.DiplomaticRelation", b =>
                {
                    b.HasOne("DiplomaticMailBot.Entities.RegisteredChat", "SourceChat")
                        .WithMany("OutgoingDiplomaticRelations")
                        .HasForeignKey("SourceChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaticMailBot.Entities.RegisteredChat", "TargetChat")
                        .WithMany("IncomingDiplomaticRelations")
                        .HasForeignKey("TargetChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceChat");

                    b.Navigation("TargetChat");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.SlotInstance", b =>
                {
                    b.HasOne("DiplomaticMailBot.Entities.RegisteredChat", "FromChat")
                        .WithMany("SlotInstancesSource")
                        .HasForeignKey("FromChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaticMailBot.Entities.SlotTemplate", "Template")
                        .WithMany("SlotInstances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaticMailBot.Entities.RegisteredChat", "ToChat")
                        .WithMany("SlotInstancesTarget")
                        .HasForeignKey("ToChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromChat");

                    b.Navigation("Template");

                    b.Navigation("ToChat");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.RegisteredChat", b =>
                {
                    b.Navigation("IncomingDiplomaticRelations");

                    b.Navigation("OutgoingDiplomaticRelations");

                    b.Navigation("SlotInstancesSource");

                    b.Navigation("SlotInstancesTarget");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.SlotInstance", b =>
                {
                    b.Navigation("DiplomaticMailCandidates");
                });

            modelBuilder.Entity("DiplomaticMailBot.Entities.SlotTemplate", b =>
                {
                    b.Navigation("SlotInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
