on:
  pull_request:
    types: [opened, reopened, synchronize]

name: run tests

permissions:
  contents: read
  actions: read
  pull-requests: read
  checks: write

jobs:
  call_reusable_run_tests:
    name: run tests
    uses: ./.github/workflows/reusable_run_tests.yml
    secrets: inherit
